apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: fraud-detection-service-4xka
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/cchase-tenant/fraud-detection-service/fraud-detection-service-4xka@sha256:57a5305f507352d4e3f313f62c7ca53e75729079445faa86f65c235bf8373913
        name: my-python
        resources: {}
status: {}
