apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fraud-detection-service-4xka
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fraud-detection-service-4xka
    app.kubernetes.io/part-of: fraud-detection-service
  name: fraud-detection-service-4xka
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: fraud-detection-service-4xka
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: fraud-detection-service-4xka
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/cchase-tenant/fraud-detection-service/fraud-detection-service-4xka@sha256:57a5305f507352d4e3f313f62c7ca53e75729079445faa86f65c235bf8373913
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
